[package]
name = "core"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
bigdecimal = { version = "0.3", features = ["serde"] }
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
mockall = "0.11"
