[package]
name = "core"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
mockall = "0.11"
frunk = "0.4.1"
frunk_core = "0.4.1"

[dev-dependencies]
tokio = { version = "1.23", features = ["macros", "rt"] }
serde_test = "1.0"
