[target.'cfg(all())']
rustflags = [
    "-Funsafe_code",
    "-Wclippy::as_conversions",
    "-Wclippy::expect_used",
    "-Wclippy::missing_panics_doc",
    "-Wclippy::panic_in_result_fn",
    "-Wclippy::panic",
    "-Wclippy::panicking_unwrap",
    "-Wclippy::todo",
    "-Wclippy::unimplemented",
    "-Wclippy::unreachable",
    "-Wclippy::unwrap_in_result",
    "-Wclippy::unwrap_used",
    "-Wclippy::use_self",
    # "-Wmissing_debug_implementations",
    # "-Wmissing_docs",
    "-Wrust_2018_idioms",
    "-Wunused_qualifications",

    # # FATAL: This is required because traits created with async_trait aren't object safe
    # "-Awhere_clauses_object_safety",
]

[alias]
gen-pg = "generate --path ../../../../connector-template -n"
